package com.health360.shared.domain;

public enum ErrorCode {
    VALIDATION_ERROR,
    DUPLICATE_EMAIL,
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    TOKEN_EXPIRED,
    FORBIDDEN,
    EMAIL_NOT_VERIFIED,
    ACCOUNT_LOCKED,
    ACCOUNT_DEACTIVATED,
    RESOURCE_NOT_FOUND,
    DUPLICATE_REGISTRATION,
    VERIFICATION_INCOMPLETE,
    SLOT_UNAVAILABLE,
    DUPLICATE_APPOINTMENT,
    DUPLICATE_REVIEW,
    REVIEW_WINDOW_CLOSED,
    FILE_TOO_LARGE,
    CANCELLATION_NOT_ALLOWED,
    INVALID_STATUS_TRANSITION,
    INTERNAL_ERROR
}
