import { Box, Stack, Typography } from '@mui/material';
import type { ClinicianBlock, LetterheadSnapshot } from '@/features/documents/api/documentsApi';

type Props = {
  clinician?: ClinicianBlock | null;
  letterhead?: LetterheadSnapshot | null;
  signatoryLabel?: string;
};

export function DocumentFooter({ clinician, letterhead, signatoryLabel }: Props) {
  const label = signatoryLabel ?? clinician?.roleLabel ?? 'Authorized signatory';
  return (
    <Box className="doc-footer" sx={{ mt: 4, pt: 2 }}>
      <Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={3}>
        <Box>
          <Typography variant="caption" color="text.secondary" display="block" sx={{ mb: 4 }}>
            {label}
          </Typography>
          <Typography variant="body2" fontWeight={600}>
            {clinician?.name ?? '________________________'}
          </Typography>
          {clinician?.registrationNumber ? (
            <Typography variant="caption" display="block">
              Reg. No: {clinician.registrationNumber}
            </Typography>
          ) : null}
          {clinician?.specialization ? (
            <Typography variant="caption" display="block">{clinician.specialization}</Typography>
          ) : null}
          {clinician?.signedAt ? (
            <Typography variant="caption" display="block" color="text.secondary">
              Signed: {clinician.signedAt}
            </Typography>
          ) : null}
        </Box>
        <Box sx={{ textAlign: { xs: 'left', sm: 'right' }, alignSelf: 'flex-end' }}>
          {letterhead?.footerText ? (
            <Typography variant="caption" display="block" color="text.secondary" sx={{ mb: 1, maxWidth: 280 }}>
              {letterhead.footerText}
            </Typography>
          ) : null}
          <Typography variant="caption" color="text.secondary" display="block">
            Generated by Health360
          </Typography>
        </Box>
      </Stack>
    </Box>
  );
}
