package com.health360.analytics.domain;

public enum MetricType {
    BMI,
    BMR,
    IDEAL_WEIGHT,
    LEAN_BODY_MASS,
    BODY_FAT_PERCENT,
    BODY_SURFACE_AREA,
    HEALTHY_WEIGHT_RANGE,
    PROTEIN_REQUIREMENT,
    WATER_INTAKE,
    DAILY_CALORIES,
    SLEEP_RECOMMENDATION,
    DAILY_STEP_GOAL,
    HEART_RATE_ZONES,
    BP_CLASSIFICATION,
    BLOOD_SUGAR_CLASSIFICATION,
    WAIST_HIP_RATIO,
    WAIST_HEIGHT_RATIO,
    WELLNESS_SCORE,
    HEALTH_RISK_SCORE,
    PROFILE_COMPLETION
}
