package com.health360.iam.domain;

public enum NotificationType {
    APPOINTMENT_CONFIRMATION,
    APPOINTMENT_REMINDER_24H,
    APPOINTMENT_REMINDER_1H,
    APPOINTMENT_CANCELLATION,
    VERIFICATION_STATUS,
    REVIEW_PROMPT,
    OPD_CALLED,
    OPD_IN_SERVICE,
    OPD_COMPLETED,
    OPD_DOCTOR_ASSIGNED,
    LAB_REPORT_READY,
    PHARMACY_MEDICINE_READY,
    FOLLOW_UP_REMINDER,
    OPD_APPROACHING
}
