package com.health360.iam.domain;

public enum NotificationType {
    APPOINTMENT_CONFIRMATION,
    APPOINTMENT_REMINDER_24H,
    APPOINTMENT_REMINDER_1H,
    APPOINTMENT_CANCELLATION,
    VERIFICATION_STATUS,
    REVIEW_PROMPT
}
